# Port of the gateway
server:
  port: 9000

# Gateway configuration
spring:
  cloud:
    gateway:
      routes:
      
        - id: prosumer_1_route
          uri: lb://prosumer-1-microservice
          predicates:
          - Path=/api/best-formation/**
          filters:
          - RewritePath=/api(?<segment>/?), $\{segment}

        - id: prosumer_3_route
          uri: lb://prosumer-3-microservice
          predicates:
          - Path=/api/formation/**
          filters:
          - RewritePath=/api(?<segment>/?), $\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh

eureka:
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
      #defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
